/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "surface-container-high": "#222a3d",
        "surface-dim": "#0b1326",
        "on-primary-fixed-variant": "#0035be",
        "on-secondary": "#3c0091",
        "error": "#ffb4ab",
        "on-tertiary-container": "#dbf4ff",
        "inverse-on-surface": "#283044",
        "on-background": "#dae2fd",
        "secondary-container": "#571bc1",
        "primary-fixed-dim": "#b8c3ff",
        "on-tertiary-fixed-variant": "#004e60",
        "on-secondary-fixed-variant": "#5516be",
        "tertiary-fixed": "#b7eaff",
        "primary-fixed": "#dde1ff",
        "surface": "#0b1326",
        "secondary-fixed": "#e9ddff",
        "surface-container-low": "#131b2e",
        "outline": "#8e90a2",
        "outline-variant": "#434656",
        "surface-bright": "#31394d",
        "background": "#0b1326",
        "tertiary": "#4cd6ff",
        "on-surface-variant": "#c4c5d9",
        "on-surface": "#dae2fd",
        "on-tertiary": "#003543",
        "surface-container": "#171f33",
        "tertiary-container": "#007792",
        "on-secondary-fixed": "#23005c",
        "surface-container-lowest": "#060e20",
        "on-tertiary-fixed": "#001f28",
        "surface-variant": "#2d3449",
        "inverse-primary": "#124af0",
        "primary-container": "#2e5bff",
        "surface-container-highest": "#2d3449",
        "on-primary": "#002388",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#001356",
        "on-secondary-container": "#c4abff",
        "tertiary-fixed-dim": "#4cd6ff",
        "secondary-fixed-dim": "#d0bcff",
        "surface-tint": "#b8c3ff",
        "on-primary-container": "#efefff",
        "primary": "#b8c3ff",
        "secondary": "#d0bcff",
        "error-container": "#93000a",
        "inverse-surface": "#dae2fd"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
